### ISSUE TITLE
UTF-8 non-ASCII chars

### ISSUE THREAD

**Issue by widzian** [starboarder2001/ansible-docgen#30]
Traceback (most recent call last):
  File "/bin/ansible-docgen", line 7, in <module>
    cli.run()
  File "/usr/lib/python2.7/site-packages/ansibledocgen/cli.py", line 44, in run
    self.formatter.write_files()
  File "/usr/lib/python2.7/site-packages/ansibledocgen/formatter/markup.py", line 115, in write_files
    p.write("%s" % line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 34: ordinal not in range(128)

**Comment by starboarder2001** [comment]
b0676052afc61d955ab9d3ae8c19b0acb6545d20 should solve your issue.  Can you checkout the branch bug/30 and test?

**Comment by widzian** [comment]
Thank you.
It's work like a charm.
